### ISSUE TITLE
README中Train表格

### ISSUE THREAD

**Issue by CrossEntropy** [whoNamedCody/Optim_Hopenet#4]
嗨 @whoNamedCody ，你的工作非常棒，感谢你提供的帮助！
我有一个问题，Train下表格是对于训练集的结果，还是针对测试集(AFLW 2000)的结果？
再一次感谢你的帮助！

**Comment by FX-STAR** [comment]
验证集：AFLW2000 的结果

**Comment by CrossEntropy** [comment]
感谢你的回复!
