### ISSUE TITLE
裁剪图像k的选取

### ISSUE THREAD

**Issue by CrossEntropy** [whoNamedCody/Optim_Hopenet#8]
嗨, @whoNamedCody .
请问, k 的选取有什么经验嘛？我在测试时发现, k=0 时 在测试集上的偏差会变大, 谢谢回答!

**Comment by FX-STAR** [comment]
k值一般取0.2-0.4，因为姿态估计还是依赖部分背景信息，所以k=0效果会差

**Comment by CrossEntropy** [comment]
嗨, @whoNamedCody .
感谢您的回复。
